ShoppingSite/Controllers/AdminChangerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;

namespace ShoppingSite.Controllers
{
    public class AdminChangerController : Controller
    {
        private O_BuyEntities db = new O_BuyEntities();

        // GET: AdminChanger
        public ActionResult Index()
        {
            var items = db.Items.Include(i => i.Category);
            return View(items.ToList());
        }

        // GET: AdminChanger/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: AdminChanger/Create
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName");
            return View();
        }

        // POST: AdminChanger/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,brandName,itemName,color,quantity,price,description,categoryId")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName", item.categoryId);
            return View(item);
        }

        // GET: AdminChanger/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName", item.categoryId);
            return View(item);
        }

        // POST: AdminChanger/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,brandName,itemName,color,quantity,price,description,categoryId")] Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoryId = new SelectList(db.Categories, "categoryId", "categoryName", item.categoryId);
            return View(item);
        }

        // GET: AdminChanger/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: AdminChanger/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingSite/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using ShoppingSite.Common;

namespace ShoppingSite.Controllers
{
    public class ItemController : Controller
    {
        O_BuyEntities db = new O_BuyEntities();
        // GET: Item
        public ActionResult AddItem()
        {
            ViewBag.Categories = DropDown.getCategory();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Additem(Item item, List<HttpPostedFileBase> images)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.Items.Add(item);
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    var errorMessages = ex.EntityValidationErrors
                        .SelectMany(x => x.ValidationErrors)
                        .Select(x => x.ErrorMessage);
                }

                if (images != null)
                {
                    foreach (var image in images)
                    {
                        var filePath = Server.MapPath(ConfigurationManager.AppSettings["ItemImagesPath"]);
                        var directory = new DirectoryInfo(filePath);
                        if (directory.Exists == false)
                        {
                            directory.Create();
                        }
                        string itemImgName = Guid.NewGuid() + image.FileName;
                        image.SaveAs(filePath + itemImgName);

                        itemImage img = new itemImage();
                        img.itemId = item.id;
                        img.address = itemImgName;
                        db.itemImages.Add(img);
                        db.SaveChanges();
                    }
                    ViewBag.Message = "True";
                }
            }
            ViewBag.Categories = DropDown.getCategory();
            return View();
        }

        public ActionResult ShowItemDetail(int itemId)
        {
            Item item = db.Items.Include("itemImages").FirstOrDefault(it => it.id == itemId);
            return View(item);
        }
    }
}

ShoppingSite/Views/Item/AddItem.cshtml
@model DataAccess.ItemMetaData

@{
    ViewBag.Title = "Add Item";

    if (ViewBag.Message != null)
    {
        <script>
            alert('Item Added Successfully !');
        </script>
    }
}

@using (Html.BeginForm("AddItem", "Item", FormMethod.Post, new { encType = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Add Item</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.brandName, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.brandName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brandName, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.itemName, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.itemName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.itemName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.price, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.description, new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="CategoryId" class="col-md-2 control-label">Category</label>
            <div class="col-md-3">
                <select id="CategoryId" name="CategoryId" class="form-control">
                    <option>Select-Category</option>
                    @foreach (var item in ViewBag.Categories)
                    {
                        <option value="@item.categoryId">@item.categoryName</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="file">Load File</label>

            <input id="images" name="images" type="file" multiple />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>

        <p>
            @Html.ActionLink("Back To List", "Index", "AdminChanger")
        </p>
    </div>
}

ShoppingSite/Views/Item/ShowItemDetail.cshtml
@using System.Configuration
@model DataAccess.Item

@{
    if (Session["userId"] != null)
    {
        Layout = null;
        Layout = "~/Views/Shared/MyLayout.cshtml";
    }
    ViewBag.Title = "ShowItemDetail";
    string url = null;
}

<h2>Item Detail</h2>

<div class="container" style="margin-top: 3%">
    <div class="row">
        <div class="col-md-4">
            @foreach (var image in Model.itemImages)
            {

                <div class="col-md-12">
                    <img src="@Url.Content(ConfigurationManager.AppSettings["ItemImagesPath"]+ image.address)" style="width: 100%;height: 400px" />
                </div>
            }
        </div>
        <div class="col-md-6">
            <div>
                <hr />
                <dl class="dl-horizontal">
                    <h2>@Model.brandName @Model.itemName</h2>
                    <br />
                    <dt>
                        @Html.DisplayNameFor(model => model.brandName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.brandName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.itemName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.itemName)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.color)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.color)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.price)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.price)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.description)
                        <!--<button type="button" value="Add to Cart" id="btnAddToCart" class="btn btn-success" style="height:50px;width:100px;">Add To Cart</button>-->
                    </dd>
                </dl>
            </div>
            <br />
            @if (Model.Category.categoryName == "Smartphones")
            {
                url = Url.Content("~/Mobile/Index");
            }else if (Model.Category.categoryName == "Men Fashion")
            {
                url = Url.Content("~/Fashion/Index");
            }
            <div style="margin-left: 15%;">
                @Html.ActionLink("Add to Cart", "AddItem", "Cart", new { prodId = Model.id, URL = url}, new { @class = "btn btn-success" })
            </div>
        </div>

    </div>
</div>